aesculapius/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('app_users.urls', namespace='api')),
    url(r'^api/session-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/token-auth/', views.obtain_auth_token),
    url(r'^', include('app_main.urls', namespace='main')),
]

app_main/urls.py
from django.conf.urls import url
import app_main.views

urlpatterns = [
    url(r'^', app_main.views.home, name='home'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Aesculapius{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="{% static 'external/css/materialize.css' %}"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
  <!--        <link type="text/css" rel="stylesheet" href="{% static 'css/style1.css' %}"  media="screen,projection"/>-->


  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <script src="{% static 'external/js/angular.min.js' %}"></script>
  <script src="{% static 'external/js/restangular.min.js' %}"></script>
  <script src="{% static 'external/js/lodash.min.js' %}"></script>
  <script src="{% static 'external/js/angular-ui-router.min.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
  {% block head %}{% endblock %}
</head>

<body>
  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="{% static 'external/js/jquery-3.0.0.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'external/js/materialize.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/init.js' %}"></script>


  <nav class="nav-wrapper grey lighten-3" role="navigation">
    <div class="nav-wrapper"><a id="logo-container" href="{% url 'main:home' %}" class="brand-logo"><img src="{% static 'img/logo.png' %}" width="250px" height="55px" VSPACE=4 ></a>
      {% if user.is_authenticated %}
      <ul id="nav" class="right">
          <span class="black-text">{{ user.employee.profile.first_name }} {% if user.employee.profile.last_name != None %}{{ user.employee.profile.last_name }}{% endif %}</span>
          <a id="login" href="/api-auth/logout/?next=/" class="tooltipped waves-effect waves-light btn-flat" onclick="$(this).closest('form').submit()" data-position="left" data-delay="50" data-tooltip="Salir"><i class="material-icons left">close</i></a>
      </ul>
      {% else %}
      <ul id="nav" class="right hide-on-med-and-down">
        <form action="/api-auth/login/" role="form" method="post">
          {% csrf_token %}
          <input name="next" value="/" type="hidden">
          <div class="tooltipped left input-field" data-position="bottom" data-delay="50" data-tooltip="Ingrese su usuario">
            <input id="search" placeholder="Usuario" name="username" type="search" required>
            <label for="search"><i class="material-icons">perm_identity</i></label>
          </div>

          <div class="tooltipped left input-field" data-position="bottom" data-delay="50" data-tooltip="Ingrese su contraseña">
            <input id="loginPassword" placeholder="Contraseña" name="password" type="password" required>
            <label for="loginPassword"><i class="material-icons">vpn_key</i></label>
          </div>

          <a id="login" class="waves-effect waves-light btn-flat" onclick="$(this).closest('form').submit()"><i class="material-icons left">send</i>Log In</a>
        </form>
      </ul>

      <ul id="nav-mobile" class="side-nav grey lighten-3">
        <form action="/api-auth/login/" role="form" method="post">
          {% csrf_token %}
          <input name="next" value="/" type="hidden">
          <div class="tooltipped left input-field" data-position="right" data-delay="50" data-tooltip="Ingrese su usuario">
            <input id="search" placeholder="Usuario" name="username" type="search" required>
            <label for="search"><i class="material-icons">perm_identity</i></label>
          </div>

          <div class="tooltipped left input-field" data-position="right" data-delay="50" data-tooltip="Ingrese su contraseña">
            <input id="loginPassword" placeholder="Contraseña" name="password" type="password" required>
            <label for="loginPassword"><i class="material-icons">vpn_key</i></label>
          </div>
          <a id="login" class="waves-effect waves-light btn-flat" onclick="$(this).closest('form').submit()"><i class="material-icons left">send</i>Log In</a>
        </form>
      </ul>
      {% endif %}
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>


  <!--<nav>
  <div class="nav-wrapper blue darken-3">
  <a href="#" class="brand-logo">Aesculapius</a>
  <ul id="nav" class="right hide-on-med-and-down">
  <a  class="waves-effect btn-flat"><i class="material-icons left">person_pin</i>Profile</a>
  <a  class="btn-flat btn-tiny waves-effect "><i class="material-icons">exit_to_app</i></a>
</div>


</nav>-->

<main>
  {% block content %}
  <div id="slide" class="slider">
    <ul class="slides">
      <li>
        <img src="{% static 'img/church.jpg' %}">
        <div id="text1" class="caption center-align card-panel">
          <h3 class="white-text text-lighten-3">Iglesia Santa Maria de la Paz</h3>
          <h5 class="white-text light">Cesar Duayen 4500, Poeta Lugones, Cordoba.</h5>
        </div>
      </li>
      <li>
        <img src="{% static 'img/remedios.jpg' %}">
        <div id="text2" class="caption center-align card-panel">
          <h3 class="white-text">Ayudanos a ayudar !</h3>
          <h5 class="white-text">Si tenes remedios que no necesitas, donalos para ayudar a los que lo necesitan.</h5>
        </div>
      </li>
      <li>
        <img src="{% static 'img/foto1.jpg' %}">
        <div id="text1" class="caption center-align card-panel">
          <h3 class="white-text">Consultoría Medica</h3>
          <h5 class="white-text">Contamos con una amplia cartilla de profesionales.</h5>
        </div>
      </li>

    </ul>
  </div>
  {% endblock %}
</main>

<footer class="page-footer grey lighten-3">
  <div class="container">
    <div class="row">
      <div class="col l9 s12">
        <h5 class="black-text">Aesculapius</h5>
        <p class="black-text">Software de consultoría médica - Parroquia Santa María de la Paz</p>


      </div>
      <div class="col l3 s12">
        <h5 class="black-text">Links</h5>
        <ul>
          <li><a class="black-text" href="http://github.com/aesculapiusteam/aesculapius">GitHub</a></li>
          <li><a class="black-text" href="https://www.facebook.com/Parroquia-Santa-Maria-de-la-Paz-495991100463679/">Facebook</a></li>
          <li><a class="black-text" href="{% url 'api:api-root' %}">API</a></li>

        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <a href="http://github.com/aesculapiusteam/" class="black-text">Made by Aesculapius Team</a>
    </div>
  </div>
</footer>

{% block scripts %}
{% endblock %}
</body>
</html>